---
title: "Day8-Data-Frame-Practice"
format: html
editor: visual
---

## Creating Data Frame

```{r}
date <- c(9,10,11,12,13,14,15)
weather <- c("sunny","hot","hot","rain","cloudy","cool","hail")
temp <- c(73,100,105,65,50,65,40)
```

```{r}
unique(weather)
```

```{r}
weather_in_noho <- data.frame(date, weather,temp)
weather_in_noho
```

```{r}
# View "date" from data frame
weather_in_noho$date

# Calculate mean
mean(weather_in_noho$date)

# Table
table(weather_in_noho$weather, weather_in_noho$temp)
```

```{r}
library(tidyverse)

glimpse(weather_in_noho)
```

```{r}
# First few rows
head(weather_in_noho)

# Last few rows
tail(weather_in_noho)

# Number of rows
nrow(weather_in_noho)

# Number of columns
ncol(weather_in_noho)

# Column names
names(weather_in_noho)
```

```{r}
# Change column names
new_names <- c("DATE", "WEATHER", "TEMP")
names(weather_in_noho) <- new_names
names(weather_in_noho)
```

## Chicken Weight Data Frame Practice

```{r}
ChickWeight
```

```{r}
# Change title to make it tidy
new_title <- c("Weight","Time","Chick","Diet")
names(ChickWeight) <- new_title
ChickWeight
```

```{r}
# Change title without manually changing each one of them
names(ChickWeight)[1] <- "Weight"
ChickWeight
```

```{r}
# Get Metadata
?ChickWeight
```

```{r}
glimpse(ChickWeight)
```

```{r}
# Scatter Plot
ggplot(ChickWeight, aes(x=Time, y=Weight)) +
  geom_point()
```

```{r}
# Simple Linear Regression (lm) where se is off (error distortion is off)
ggplot(ChickWeight, aes(x=Time, y=Weight)) +
  geom_point() +
  geom_smooth(method = "lm", se=FALSE)
```

```{r}
# Lowess
ggplot(ChickWeight, aes(x=Time, y=Weight)) +
  geom_point() +
  geom_smooth(method = "loess")
```